# Generated by Django 4.1.4 on 2023-07-15 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Guruh nomi')),
                ('price', models.IntegerField(default=0, verbose_name="Guruh to'lovi")),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Fan nomi')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('fullname', models.CharField(max_length=200, verbose_name="To'liq Ism Familiya")),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='Familiya')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='Familiya')),
                ('fullname', models.CharField(max_length=200, null=True, verbose_name="To'liq Ism va Familiya")),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group')),
            ],
            options={
                'unique_together': {('fullname', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('month', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(verbose_name="To'lov")),
                ('note', models.TextField(verbose_name="Eslatma / To'lov tarifi")),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name="To'lov vaqti")),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqt")),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pupil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pupil')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject', verbose_name='Fan nomi'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher', verbose_name="O'qituvchisi"),
        ),
    ]
